# Generated by Django 4.0.3 on 2022-04-28 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='город')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Regin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='область')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='навык')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
            },
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='логин')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес эл. почты')),
                ('avatar', models.ImageField(blank=True, upload_to=users_app.models.path_to_user_avatar_directory, verbose_name='фото профиля')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('is_hairdresser', models.BooleanField(default=False, verbose_name='парикмахер')),
                ('date_of_registration', models.DateField(auto_now_add=True, verbose_name='дата регистрации')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'простого пользователя',
                'verbose_name_plural': 'простые пользователи',
            },
        ),
        migrations.CreateModel(
            name='Hairdresser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('rating', models.IntegerField(default=1, verbose_name='рейтинг')),
                ('instagram', models.URLField(blank=True, max_length=255, verbose_name='инстаграм')),
                ('another_info', models.TextField(blank=True, max_length=1000, verbose_name='дополнительная информация')),
                ('portfolio', models.ImageField(blank=True, upload_to=users_app.models.path_to_user_portfolio_directory, verbose_name='портфолио')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users_app.city')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_app.simpleuser')),
                ('skills', models.ManyToManyField(to='users_app.skill', verbose_name='навыки')),
            ],
            options={
                'verbose_name': 'парикмахер',
                'verbose_name_plural': 'парикмахеры',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_app.regin', verbose_name='область'),
        ),
    ]
