# Generated by Django 4.0.3 on 2022-04-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regin',
            new_name='Region',
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'область', 'verbose_name_plural': 'области'},
        ),
    ]
