# Generated by Django 4.0.3 on 2022-05-04 13:28

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_rename_regin_region_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='default_avatar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='avatar',
            field=models.ImageField(blank=True, default='..\\static\\users_app\\assets\\img\\default_photo.jpg', upload_to=users_app.models.path_to_user_avatar_directory, verbose_name='фото профиля'),
        ),
    ]
