# Generated by Django 4.0.3 on 2022-05-14 00:25

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_alter_skill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'навык', 'verbose_name_plural': 'навыки'},
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='avatar',
            field=models.ImageField(blank=True, default='../static\\users_app\\assets\\img\\default_photo.jpg', upload_to=users_app.models.path_to_user_avatar_directory, verbose_name='фото профиля'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='адрес эл. почты'),
        ),
    ]
