# Generated by Django 4.0.3 on 2022-08-09 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0007_alter_skill_options_alter_simpleuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='users_app.region', verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hairdresser', to='users_app.city'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hairdresser', to='users_app.simpleuser'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='skills',
            field=models.ManyToManyField(related_name='hairdressers', to='users_app.skill', verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simpleuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
