# Generated by Django 4.0.3 on 2022-08-14 12:37

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_city_region_alter_hairdresser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdresser',
            name='another_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='инстаграм'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='portfolio',
            field=models.ImageField(blank=True, null=True, upload_to=users_app.models.path_to_user_portfolio_directory, verbose_name='портфолио'),
        ),
    ]
