# Generated by Django 4.1.1 on 2022-09-25 07:37

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_alter_hairdresser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/users_app/assets/img/default_photo.jpg', upload_to=users_app.models.path_to_user_avatar_directory, verbose_name='фото профиля'),
        ),
    ]
