# Generated by Django 4.0.3 on 2022-03-31 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Hairdresser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес эл. почты')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Фото профиля')),
                ('rating', models.IntegerField(default=1, verbose_name='Рейтинг')),
                ('instagram', models.URLField(blank=True, max_length=255, verbose_name='Инстаграм')),
                ('another_info', models.TextField(blank=True, max_length=1000, verbose_name='Дополнительная информация')),
                ('portfolio', models.ImageField(blank=True, upload_to='portfolio/%Y/%m/%d/', verbose_name='Портфолио')),
                ('date_of_registration', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_app.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(to='users_app.skill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Парикмахера',
                'verbose_name_plural': 'Парикмахеры',
            },
        ),
    ]
