# Generated by Django 4.0.3 on 2022-04-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdresser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users_app.city'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='skills',
            field=models.ManyToManyField(to='users_app.skill', verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='адрес эл. почты'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
    ]
