# Generated by Django 4.0.3 on 2022-03-31 19:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_hairdresser_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='another_info',
            field=models.TextField(blank=True, max_length=1000, verbose_name='дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d/', verbose_name='фото профиля'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users_app.city'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='date_of_registration',
            field=models.DateField(auto_now_add=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='фдрес эл. почты'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, verbose_name='инстаграм'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='name',
            field=models.CharField(max_length=30, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='portfolio',
            field=models.ImageField(blank=True, upload_to='portfolio/%Y/%m/%d/', verbose_name='портфолио'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users_app.skill', verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='hairdresser',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='навык'),
        ),
    ]
