# Generated by Django 4.0.3 on 2022-03-31 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_city_name_alter_hairdresser_another_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdresser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users_app.city'),
        ),
    ]
