# Generated by Django 4.0.3 on 2022-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_city_options_alter_hairdresser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdresser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='hairdresser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hairdresser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hairdresser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='hairdresser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating_value',
            field=models.IntegerField(verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=8000, verbose_name='добавить отзыв'),
        ),
    ]
