# Generated by Django 4.0.3 on 2022-04-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_hairdresser_avatar_remove_hairdresser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
