# Generated by Django 4.0.3 on 2022-04-28 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='автор')),
                ('text', models.TextField(max_length=8000, verbose_name='добавить отзыв')),
                ('rating_value', models.IntegerField(verbose_name='оценка')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.hairdresser', verbose_name='кому')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
